[theme]
# The primary color is a dark green, which is a good primary color for an agriculture theme
primaryColor = "#2E8B57" 
backgroundColor = "#F0FFF0"  # A light, airy green for the background
secondaryBackgroundColor = "#E0FFE0" # A slightly darker green for contrast
textColor = "#333333"       # A dark gray for text, which is easier to read than pure black
font = "sans serif"
